### ISSUE TITLE
Out of date Mono.Cecil dll

### ISSUE THREAD

**Issue by amcorch** [csnemes/tracer#68]
I'm suddenly getting an error when trying to build my application that is using Tracer.Serilog.Fody:

Fody: The weaver assembly 'Tracer.Fody, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '1C-A0-91-87-7D-12-CA-03' but got '50-CE-BF-1C-CE-B9-D0-5E'. The weaver needs to update to at least version 3.0 of FodyHelpers.

This error was not occurring a few days ago, and I have not changed anything involving Fody. I am currently using Tracer.Serilog.Fody version 2.2.0

Is anyone else experiencing this? Or does anyone know how to fix this error?

**Comment by csnemes** [comment]
You should update to the latest Tracer.Fody 2.2.0, it should solve the problem.

**Comment by amcorch** [comment]
I'm already using Tracer.Serilog.Fody 2.2.0 in my project. I just added Tracer.Fody 2.2.0 as well, but I am still getting the same error. 

Is there any sort of temporary file that I might be causing this error that I could delete?

**Comment by amcorch** [comment]
I deleted some old temp files and nuget cache files and the build is now working. I'm not sure why this suddently popped up.
